version: '3.8'

services:
  app:
    build:
      context: .
      target: app-builder
    container_name: app
    depends_on: 
      - mysql
    volumes:
      - .:/go/src/dropit
    ports:
      - 8000:8000
    env_file:
      - .env
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dropit
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    # This command overwrite the sql_mode,
    # Here we are disabling "ONLY_FULL_GROUP_BY" default flag, in order to avoid the reference of 
    # all select statements in the "GROUP BY" clause
    command:
      --default-authentication-plugin=mysql_native_password
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
  db_reload:
    build: 
      context: .
      target: db-builder
    container_name: db_reload
    depends_on: 
      - mysql
    volumes:
      - .:/go/src/dropit
    env_file:
      - .env

volumes:
  my-db:
